# Generated by Django 4.2.1 on 2023-06-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_image_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_images/default-avatar.jpg', upload_to='profile_images/'),
        ),
    ]
